"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Flights",
      [
        {
          airplane_id: 1,
          departure: 1,
          destination: 2,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 100,
          price: 1500000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 2,
          departure: 1,
          destination: 3,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 120,
          price: 1300000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 3,
          departure: 2,
          destination: 4,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 80,
          price: 2000000,
          operation_status: "true",
          region_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 4,
          departure: 3,
          destination: 5,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 90,
          price: 1200000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 5,
          departure: 1,
          destination: 6,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 150,
          price: 1800000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 2,
          departure: 4,
          destination: 7,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 110,
          price: 1400000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 3,
          departure: 2,
          destination: 8,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 70,
          price: 1900000,
          operation_status: "true",
          region_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 4,
          departure: 5,
          destination: 9,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 85,
          price: 1300000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 5,
          departure: 1,
          destination: 10,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 120,
          price: 1700000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          airplane_id: 2,
          departure: 3,
          destination: 6,
          departure_date: new Date(),
          arrival_date: new Date(),
          departure_time: '09:00',
          arrival_time: '15:00',
          available_seats: 95,
          price: 1400000,
          operation_status: "true",
          region_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Flights", null, {});
  },
};